const localization = {
  en: {
    'Aplikasi Catatan': 'Notes App',
    'Catatan Aktif': 'Active Notes',
    'Arsip': 'Archives',
    'Memuat': 'Loading',
    'Cari berdasarkan judul': 'Search by title',
    'Judul': 'Title',
    'Isi catatan': 'Body',
    'Tidak ada catatan': 'No items available',
    'Sudah punya akun?': 'Already have an account?',
    'Login di sini': 'Login here',
    'Belum punya akun?': 'Don\'t have an account?',
    'Daftar di sini': 'Register here',
    'Anda tidak diperkenankan untuk mengakses catatan ini': 'You are not allowed to access this note',
    'Konfirmasi': 'Confim to delete',
    'Apakah anda yakin ingin menghapus catatan ini?': 'Are you sure to delete this note?',
    'Ya': 'Yes',
    'Tidak': 'No',
    'Batal': 'Cancel',
    'Catatan berhasil diaktifkan': 'Note activated successfully',
    'Catatan berhasil diarsipkan': 'Note archived successfully',
    'Catatan berhasil ditambahkan': 'Note created successfully',
    'Catatan berhasil dihapus': 'Note deleted successfully',
    'Silakan lengkapi seluruh form': 'Please fill all fields',
    'Lemah': 'Weak',
    'Oke': 'Okay',
    'Bagus': 'Good',
    'Kuat': 'Strong',
    'Terlalu Pendek': 'Too Short',
    'Menginisiasi': 'Initializing',
    'Proses pendaftaran berhasil': 'The registration process is success',
    'Password tidak sesuai':  'Password doesn\'t match',
  }
};

export default localization;
